services:
  dp:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ahmedraslan
      POSTGRES_PASSWORD: admin
    volumes:
      - dp:/var/lib/postgresql/data
    networks:
      - dp

  customers-api:
    container_name: customers-management-api
    image: ahmedraslan28/customer-management-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dp:5432/customer
    ports:
      - "8081:8080"
    networks:
      - dp

    depends_on:
      - dp
    restart: unless-stopped




volumes:
  dp:

networks:
  dp: